server:
  port: 8081

spring:
  application:
    name: short-link-manager
  datasource:
    url: jdbc:mysql://localhost:3306/short_link?createDatabaseIfNotExist=true
    username: root
    password: Armin#123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  liquibase:
    change-log: db/changelog/changelog-master.xml

neshan:
  secret: secreTkjh15H7uJhgSHOP0plFkjtuwerqJm5Oop7wWwlkHQasY

logging:
  level:
    com:
      neshan: debug
    liquibase: info